print('-'*35)
print("Tugas SISOP Kelas-B")
print('-'*35)
print("Nama	: M. Awaluddin ilham zuhri")
print("NPM	: 21083010112")
print('-'*35)
print(" notes: ")
print("-"*35)
print("Halo Dunia")
print("ini adalah skrip Bash pertamaku di Linux")
